cimobgrupo2/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using System.IO;
using Microsoft.AspNetCore.Http;
using cimobgrupo2.Models;
using cimobgrupo2.Models.FilesViewModels;
using cimobgrupo2.Extensions;

namespace cimobgrupo2.Controllers
{
    /// <summary>Controlador para ficheiros</summary>
    /// <remarks>Extende de BaseController</remarks>
    public class FileController: Controller
    {
        /// <summary>Atributo para o File Provider</summary>
        private readonly IFileProvider fileProvider;
        /// <summary>Construtor com parametros - FileController</summary>
        /// <param name="fileProvider">File Provider</param>
        public FileController(IFileProvider fileProvider)
        {
            this.fileProvider = fileProvider;
        }

        /// <summary>Método responsável por dar upload num ficheiro</summary>
        /// <param name="path">Caminho para onde o ficheiro será carregado</param>
        /// <param name="file">Ficheiro a ser carregado</param>
        /// <returns>True se foi carregado com sucesso e falso caso contrário</returns>
        public async Task<bool> UploadFile(string path, IFormFile file)
        {
            if (file == null || file.Length == 0)
                return false;

            Directory.CreateDirectory(path);

            path = Path.Combine(path, file.GetFilename());

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            return true;
        }

        /// <summary>Método responsável por obter um ficheiro, num determinado caminho</summary>
        /// <param name="path">Caminho onde o ficheiro está presente</param>
        /// <param name="fileName">Nome do ficheiro a ser extraído</param>
        /// <returns>FileDetails do ficheiro, se existe</returns>
        public FileDetails GetFile(string path, string fileName)
        {
            var model = new FileDetails();
            foreach (var item in this.fileProvider.GetDirectoryContents(path))
            {
                if (item.Name == fileName)
                {
                    model.Name = fileName;
                    model.Path = item.PhysicalPath;
                    return model;
                }
            }
            return null;
        }

        /// <summary>Método responsável por obter uma lista de ficheiros presentes num diretório</summary>
        /// <param name="path">Caminho de onde queremos a lista de ficheiros</param>
        /// <param name="nameException">Nome de um ficheiro que não se quer na lista</param>
        /// <returns>Lista dos vários ficheiros presentes nesse caminho (Lista de FileDetails)</returns>
        public List<FileDetails> GetFiles(string path, string nameException = null)
        {
            var model = new List<FileDetails>();
            foreach (var item in this.fileProvider.GetDirectoryContents(path))
            {
                if (item.Name != nameException)
                {
                    model.Add(
                   new FileDetails { Name = item.Name, Path = item.PhysicalPath });
                }
               
            }
            return model;
        }

        /// <summary>Action responsável pelo download de um ficheiro</summary>
        /// <param name="tipo">Tipo de ficheiro (se pertence a uma candidatura ou programa)</param>
        /// <param name="id">Id do programa/candidatura a que pertence</param>
        /// <param name="nome">Nome do ficheiro</param>
        /// <returns>Download do ficheiro para o pc</returns>
        public async Task<IActionResult> Download(string tipo, string id,  string nome)
        {
            if (tipo == null || nome == null)
                return Content("filename not present");

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files", tipo, id, nome);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        /// <summary>Action responsável pela eliminação de um ficheiro</summary>
        /// <param name="path">Caminho (pasta onde o ficheiro está presente)</param>
        /// <param name="filename">Nome do ficheiro que se pretende eliminar</param>
        /// <returns>Redirecciona para a action Files</returns>
        public IActionResult Delete(string path, string filename)
        {
            if (filename == null)
                return Content("filename not present");


            path = Path.Combine(path, filename);

            if ((System.IO.File.Exists(path)))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Files");
        }

        /// <summary>Método para obter o tipo de conteudo (extensao) de um ficheiro</summary>
        /// <param name="path">Caminho do ficheiro</param>
        /// <returns>Extensão do ficheiro</returns>
        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        /// <summary>Método para obter uma lista dos tipos de ficheiro permitidos</summary>
        /// <returns>Lista de tipos</returns>
        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }
    }
}

cimobgrupo2/Controllers/ProgramasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using cimobgrupo2.Models;
using cimobgrupo2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using cimobgrupo2.Models.FilesViewModels;
using cimobgrupo2.Extensions;

namespace cimobgrupo2.Controllers
{
    /// <summary>Controlador para programas</summary>
    /// <remarks>Extende de BaseController</remarks>
    public class ProgramasController : BaseController
    {
        /// <summary>Atributo para o caminho base de gravação de ficheiros associados a programas</summary>
        private string BASE_PATH = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files", "programas");

        /// <summary>Atributo para a lista de programas</summary>
        private List<Programa> _programas;

        /// <summary>Construtor com parametros - ProgramasController</summary>
        /// <param name="context">Context da Bd</param>
        /// <param name="fileProvider">File Provider</param>
        public ProgramasController(ApplicationDbContext context, IFileProvider fileProvider) : base(context, fileProvider, "Programas")
        {
            _programas = context.Programas.Include(e => e.EscolasParceiras).ThenInclude(e => e.EscolaParceira)
                .ThenInclude(e => e.Cursos).ThenInclude(e => e.Curso).ToList();
        }

        /// <summary>Action que prepara e mostra o index</summary>
        /// <returns>Retorna a view</returns>
        public IActionResult Index()
        {
            SetHelpModal("Index");
            return View(ProperView("Index"), _programas);
        }

        /// <summary>Action responsável por preparar e mostrar a página de detalhes de um programa</summary>
        /// <param name="id">id do programa cujos detalhes se pretendem visualizar</param>
        /// <returns>Caso o programa seja válido, retorna a view de detalhes do mesmo. Caso contrário redirecciona para o index</returns>
        public IActionResult Detalhes(int? id)
        {
            Programa programa = _programas.Find(p => p.ProgramaId == id);
            if (programa != null)
            {
                SetHelpModal("Detalhes");
                var caminho = "programas/" + id;
                ViewBag.Edital = _fileController.GetFile(caminho, programa.Edital);
                ViewBag.Documentos = _fileController.GetFiles(caminho, programa.Edital);
                return View(ProperView("Detalhes"), programa);
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>Action responsável por preparar e exibir a página de criação de programa</summary>
        /// <returns>View com o formulário de criação</returns>
        public IActionResult Adicionar()
        {
            SetHelpModal("Adicionar");
            SetHelpTooltips();
            return View(ProperView("Adicionar"));
        }

        /// <summary>Action que trata da criação de um programa e da sua adição à bd</summary>
        /// <param name="Programa">Bind dos campos do formulário preenchidos pelo utilizador, num objeto Programa</param>
        /// <param name="file">Edital do programa</param>
        /// <returns>Redireciona para a acção Index, se adicionada com sucesso.</returns>
        [HttpPost]
        public async Task<IActionResult> Adicionar([Bind("ProgramaId,Nome,Duracao,Descricao")] Programa Programa, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Programa);
                _context.SaveChanges();

                if (file != null)
                {
                    Programa.Edital = file.GetFilename();

                    var caminho = Path.Combine(BASE_PATH, Programa.ProgramaId.ToString());
                    await _fileController.UploadFile(caminho, file);
                }

                _context.SaveChanges();
                SetSuccessMessage("Programa adicionado.");
                return RedirectToAction(nameof(Index));
            }
            SetErrorMessage("003");
            SetHelpModal("Adicionar");
            SetHelpTooltips();
            return View(Programa);
        }

        /// <summary>Action responsável por preparar e exibir a página de edição de programa</summary>
        /// <param name="Id">Id do programa a editar</param>
        /// <returns>View com o formulário de edição</returns>
        public IActionResult Editar(int? Id)
        {
            Programa Programa = _context.Programas.SingleOrDefault(p => p.ProgramaId == Id);
            ViewBag.EscolasAssociar = _context.EscolasParceiras.Where(e => e.Programas.Where(p => p.Programa == Programa).Count() == 0);

            var caminho = "programas/" + Id;
            ViewBag.Edital = _fileController.GetFile(caminho, Programa.Edital);
            ViewBag.Documentos = _fileController.GetFiles(caminho, Programa.Edital);
            SetHelpModal("Editar");
            SetHelpTooltips();
            return View(ProperView("Editar"), Programa);
        }

        /// <summary>Action que trata da edição de um programa e da sua atualização na bd</summary>
        /// <param name="Programa">Bind dos campos do formulário preenchidos pelo utilizador, num objeto Programa</param>
        /// <param name="file">Ficheirod do edital do programa</param>
        /// <returns>Redireciona para a acção Index, se editada com sucesso</returns>
        [HttpPost]
        public async Task<IActionResult> Editar([Bind("ProgramaId,Nome,Duracao,Descricao")] Programa Programa, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                Programa atual = _context.Programas.SingleOrDefault(p => p.ProgramaId == Programa.ProgramaId);
                atual.Nome = Programa.Nome;
                atual.Duracao = Programa.Duracao;
                atual.Descricao = Programa.Descricao;


                if (file != null)
                {
                    var caminho = Path.Combine(BASE_PATH, atual.ProgramaId.ToString());
                    _fileController.Delete(caminho, atual.Edital);
                    atual.Edital = file.GetFilename();
                    await _fileController.UploadFile(caminho, file);
                }

                _context.SaveChanges();
                SetSuccessMessage("Programa editado.");
                return RedirectToAction(nameof(Index));
            }

            SetErrorMessage("003");
            SetHelpModal("Editar");
            SetHelpTooltips();
            return View(Programa);
        }

        /// <summary>Action responsável por exibir o modal de confirmação de remoção de programa</summary>
        /// <param name="Id">Id do programa a remover</param>
        /// <returns>Partialview com o devido modal</returns>
        public IActionResult RemoverModal(int? Id)
        {
            return PartialView(ProperView("RemoverModal"), _context.Programas.SingleOrDefault(p => p.ProgramaId == Id));
        }

        /// <summary>Action que trata da remoção de um problema da bd</summary>
        /// <param name="ProgramaId">Id do programa a remover</param>
        /// <returns>Redireciona para a acção Index</returns>
        public IActionResult Remover(int ProgramaId)
        {
            _context.Programas.Remove(_context.Programas.SingleOrDefault(p => p.ProgramaId == ProgramaId));
            _context.SaveChanges();

            foreach (FileDetails f in _fileController.GetFiles("programas/" + ProgramaId))
            {
                _fileController.Delete(Path.Combine(BASE_PATH, ProgramaId.ToString()), f.Name);
            }

            SetSuccessMessage("Programa removido.");
            return RedirectToAction(nameof(Index));
        }

        /// <summary>Action responsável por desassociar escolas de um determinada programa</summary>
        /// <param name="ProgramaId">Id do programaa</param>
        /// <param name="escolasRemover">Lista com ids das escolas a desassociar</param>
        /// <returns>Redireciona para a action de editar de determinado programa</returns>
        public IActionResult RemoverAssociacoes(int ProgramaId, int[] escolasRemover)
        {
            if (escolasRemover.Count() > 0)
            {
                Programa Programa = _context.Programas.SingleOrDefault(p => p.ProgramaId == ProgramaId);
                foreach (int i in escolasRemover)
                {
                    Programa.EscolasParceiras.Remove(Programa.EscolasParceiras.SingleOrDefault(e => e.ProgramaId == ProgramaId && e.EscolaParceiraId == i));

                }
                _context.SaveChanges();
                SetSuccessMessage(escolasRemover.Count() + " associações removidas.");
            }
            return RedirectToAction(nameof(Editar), new { Id = ProgramaId });
        }


        /// <summary>Action responsável por remover e desassociar uma lista de ficheiros, de um determinado programa</summary>
        /// <param name="ProgramaId">Id do programa</param>
        /// <param name="ficheirosRemover">Lista de ficheiros a desassociar</param>
        /// <returns>Redireciona para a action Editar de um determinado programa, já com os ficheiros removidos</returns>
        public IActionResult RemoverDocumentos(int ProgramaId, string[] ficheirosRemover)
        {
            if (ficheirosRemover.Count() > 0)
            {
                var caminho = Path.Combine(BASE_PATH, ProgramaId.ToString());
                foreach (string s in ficheirosRemover)
                {

                    _fileController.Delete(caminho, s);

                }
                SetSuccessMessage(ficheirosRemover.Count() + " documentos removidos.");
            }
            return RedirectToAction(nameof(Editar), new { Id = ProgramaId });
        }

        /// <summary>Action responsável por carregar e associar uma lista de ficheiros submetidos pelo utilizador ao programa</summary>

cimobgrupo2/Views/Programas/Cimob/Adicionar.cshtml
@model cimobgrupo2.Models.Programa

@{
    ViewData["Titulo"] = "Novo Programa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="Adicionar" method="post" enctype="multipart/form-data">
    <div class="col-md-3 col-lg-3">

        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>:
            <input asp-for="Nome" class="form-control" data-toggle="tooltip" data-placement-md="right" data-placement-xs="top" title="@ViewData["Nome"]"/>
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Duracao" class="control-label"></label>:
            <input asp-for="Duracao" class="form-control" data-toggle="tooltip" data-placement-md="right" data-placement-xs="top" title="@ViewData["Duracao"]"/>
            <span asp-validation-for="Duracao" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Edital" class="control-label"></label>:
            <input id="input-edital" name="file" type="file" class="file" data-show-preview="false" data-toggle="tooltip" data-placement-md="right" data-placement-xs="top" title="@ViewData["EditalTooltip"]">
            <span asp-validation-for="Edital" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="Descricao" class="control-label"></label>:
            <textarea asp-for="Descricao" class="form-control" style="min-height: 240px" data-toggle="tooltip" data-placement-md="right" data-placement-xs="top" title="@ViewData["Descricao"]"></textarea>
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-12 col-lg-12 botoes">
        <button type="submit" class="pull-right" id="btnConfirmar" style="margin-bottom: 20px;">Confirmar</button>
        <button type="button" onclick="location.href='@Url.Action("Index", "Programas")'" class="pull-right" id="btnVoltar">Voltar</button>
    </div>
</form>

<script>
    $("#input-edital").fileinput({
        'showUpload': false, language: "pt"
    });
</script>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

cimobgrupo2/Views/Programas/Cimob/Detalhes.cshtml
@model cimobgrupo2.Models.Programa
@{
    ViewData["Titulo"] = "Detalhes de Programa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-3 col-lg-3 left-info">
    <table id="table-info">
        <tr>
            <td><strong>Programa: </strong></td>
            <td>@Html.DisplayFor(model => model.Nome)</td>
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.Duracao): </strong></td>
            <td>@Html.DisplayFor(model => model.Duracao)</td>
        </tr>
        <tr>
            <td><strong>Edital: </strong></td>
            <td>
                @{
                    if (ViewBag.Edital != null)
                    {
                        <a href="@Url.Action("Download", "File", new { tipo = "programas", id = Model.ProgramaId, nome = ViewBag.Edital.Name })">@ViewBag.Edital.Name</a>
                    }
                    else
                    {
                        <span>(Nenhum)</span>
                    }
                }

            </td>
        </tr>

    </table>
    <p><strong>Documentos Necessários:</strong></p>
    @{
        if (ViewBag.Documentos.Count > 0)
        {


            <table class="table table-striped table-bordered">
                <tbody>
                    @{
                        foreach (var item in ViewBag.Documentos)
                        {
                            <tr>
                                <td>
                                    @item.Name
                                </td>
                                <td class="text-center"><a href="@Url.Action("Download", "File", new { tipo = "programas", id = Model.ProgramaId, nome = item.Name })"><span class="glyphicon glyphicon-download"></span></a></td>
                            </tr>

                        }
                    }
                </tbody>
            </table>
                        }
                        else
                        {
                            <p>(Nenhum)</p>

                        }
    }




    <p><strong>@Html.DisplayNameFor(model => model.Descricao):</strong></p>
    <p style="text-align:justify;">@Html.DisplayFor(model => model.Descricao)</p>
</div>

<div class="col-md-9 col-lg-9">
    <div class="sec-title" style="margin-bottom: 10px;"><span class="glyphicon glyphicon-education"></span><strong> Escolas Disponíveis:</strong></div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered" id="tabela-escolas">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        País
                    </th>
                    <th>
                        Localidade
                    </th>
                    <th>
                        Cursos
                    </th>
                    <th>
                        Vagas
                    </th>
                    <th class="no-sort"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.EscolasParceiras.ToList())
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.EscolaParceira.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EscolaParceira.Pais)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EscolaParceira.Localidade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EscolaParceira.Cursos.Count)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumeroVagas)
                        </td>
                        <td class="text-center">
                            <a asp-action="Detalhes" asp-controller="EscolasParceiras" asp-route-id="@item.EscolaParceiraId">Detalhes</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-12 col-lg-12" style="margin-top: 15px;">
    <a type="button" href="@Url.Action("RemoverModal", "Programas", new { Id = Model.ProgramaId })" data-target="#removerPrograma" data-toggle="modal" class="button pull-right" id="btnEliminar">Eliminar</a>
    <button type="button" onclick="location.href='@Url.Action("Editar", "Programas", new { Id = Model.ProgramaId })'" class="pull-right" id="btnEditar">Editar</button>
    <button type="button" onclick="javascript:history.back(); return false;" class="pull-right" id="btnVoltar" style="margin-bottom: 20px;">Voltar</button>
</div>

<div class="modal fade" id="removerPrograma" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#tabela-escolas').DataTable({
            "language": {
                "url": "/lib/DataTables/pt.json"
            },
            "searching": false,
            "pageLength": 5,
            "bLengthChange": false,
            "bFilter": true,
            "bAutoWidth": false
        });
    });
</script>

cimobgrupo2/Views/Programas/Cimob/EditarVagasModal.cshtml
@model cimobgrupo2.Models.ProgramaEscolaParceira

<form class="form-horizontal" role="form" asp-action="EditarVagas" method="POST" id="editarVagasForm">
        <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar Vagas</h4>
            </div>
    <div class="modal-body">

        <input type="hidden" asp-for="ProgramaId" />
        <input type="hidden" asp-for="EscolaParceiraId" />
        <div class="form-group">
            <div class="col-md-12 col-lg-12">
                <label class="control-label">Programa:</label>
                <input asp-for="Programa.Nome" class="form-control" disabled />
            </div>
        </div>
        <div class="form-group ">
            <div class="col-md-12 col-lg-12">
                <label class="control-label">Escola Parceira:</label>
                <input asp-for="EscolaParceira.Nome" class="form-control" disabled />
                </div>
            </div>
        <div class="form-group ">
            <div class="col-md-12 col-lg-12">
                <label class="control-label">Número de Vagas:</label>
                <input asp-for="NumeroVagas" class="form-control" />
            </div>
        </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button id="btnConfirmar" type="submit" class="btn btn-primary">Confirmar</button>
            </div>
</form>

cimobgrupo2/Views/Programas/Cimob/Index.cshtml
@model IEnumerable<cimobgrupo2.Models.Programa>
@{
    ViewData["Titulo"] = "Lista de Programas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ResultMessage")

<table class="table table-striped" id="tabela-programas">
    <thead class="thead-inverse">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duracao)
            </th>
            <th>
                Escolas Disponíveis
            </th>
            <th class="no-sort"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duracao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EscolasParceiras.Count)
                </td>
                <td class="text-center">
                    <a asp-action="Detalhes" asp-route-id="@item.ProgramaId">Detalhes</a> |
                    <a asp-action="Editar" asp-route-id="@item.ProgramaId">Editar</a> |
                    <a asp-action="RemoverModal" data-target="#removerPrograma" data-toggle="modal" asp-route-id="@item.ProgramaId">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="col-md-12 col-lg-12 botoes">
    <button type="button" onclick="location.href='@Url.Action("Adicionar", "Programas")'" class="pull-right" id="btnCriar" style="margin-bottom: 20px;">Novo Programa</button>
</div>

<div class="modal fade" id="removerPrograma" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#tabela-programas').DataTable({
            "language": {
                "url": "/lib/DataTables/pt.json"
            }
        }); 
    });

    $(function () {
        $('#removerPrograma').on('hidden.bs.modal', function () {
            // remove the bs.modal data attribute from it
            $(this).removeData('bs.modal');
            // and empty the modal-content element
            $('#removerPrograma .modal-content').empty();
        });
    });
</script>

cimobgrupo2/Views/Programas/Cimob/RemoverModal.cshtml
@model cimobgrupo2.Models.Programa

<form class="form-horizontal" role="form" asp-action="Remover" method="POST" id="removerProgramaForm">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Remover Programa</h4>
    </div>
    <div class="modal-body">
        <input type="hidden" asp-for="ProgramaId" />
        <div class="form-group animated fadeIn">
            <div class="col-md-12 col-lg-12 text-center">
                <label>Tem a certeza que pretende remover este programa?</label>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button id="btnConfirmar" type="submit" class="btn btn-primary">Confirmar</button>
    </div>
</form>